name: aus-pos-data-gen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - faker>=18.0.0
  - pydantic>=2.0.0
  - pathlib
  - python-dateutil
  - pytz
  - tzdata
  - openpyxl>=3.1.0
  - pyarrow>=14.0.0
  - fastparquet>=2023.10.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=23.0.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  - loguru>=0.7.0
  - rich>=13.7.0
  - typer>=0.9.0
  - questionary>=2.0.0
