"""
Australian POS Transaction Dataset Generator

A comprehensive synthetic data generator for Australian Point-of-Sale transactions
that complies with Australian taxation requirements and retail business practices.

This package generates realistic transaction data including:
- Sales transactions with proper GST calculations
- Return transactions with Australian business rules
- Customer and business information
- Payment method distributions
- Seasonal and temporal patterns
"""

__version__ = "0.1.0"
__author__ = "Generated by AI Assistant"
__email__ = "dev@example.com"

from .config import POSGeneratorConfig as Config
from .generator import POSDataGenerator
from .models import (
    Transaction,
    TransactionItem,
    ReturnTransaction,
    Customer,
    Business,
    PaymentMethod,
)
from .validators import ABNValidator, GSTCalculator

__all__ = [
    "Config",
    "POSDataGenerator",
    "Transaction",
    "TransactionItem",
    "ReturnTransaction",
    "Customer",
    "Business",
    "PaymentMethod",
    "ABNValidator",
    "GSTCalculator",
]
